name: Teste-lvl-4

on:
  workflow_dispatch:  

jobs:
  level1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test lvl 4
        run: vendor/bin/phpstan analyse src --level 4
