name: Test, Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

# Teste unitário

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install express jest

      - name: Teste unitário
        run: npm test

# Build

      - name: Build
        run: npm run build

# Deploy to Azure VM

      - name: Deploy to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_VM}}
          username: ${{ secrets.SSH_USERNAME }}  #teste
          key: ${{ secrets.SSH_PRIVATE_KEY }}    
          port: 22
          source: "./src"  
          target: "/home/piter/app"    