name: Teste-lvl-1

workflow_dispatch:

jobs:
  level1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test lvl 1
        run: vendor/bin/phpstan analyse src --level 1
